### ISSUE TITLE
Cant remove a listener from priority signal

### ISSUE THREAD

**Issue by Fraggle** [paulmoore/Java-Signals#1]
Hi,

The way the PrioritySignal works : create a wrapper PrioritySlot on the listener and adding it to the listener queue, I dont think it works when i remove() the listener from the priority slot as the listener is != than the created priorityslot.
Maybe I'm doing it all wrong?

Thanks,

Sebastien

**Comment by paulmoore** [comment]
Thanks for finding this!  Looking into it now.

**Comment by paulmoore** [comment]
Yup, you were right, the slot was not properly being removed from the priority queue.
